on:
  email:
    imap:
      host: outlook.office365.com
      user: ${{secrets.EMAIL_USER}}
      password: ${{secrets.EMAIL_PASSWORD}}
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          SUBJECT: ${{(on.email.outputs.subject)}}
          DUE: ${{(on.email.outputs.date)}}
          CONTENT: ${{(on.email.outputs.textAsHtml)}}
          SENDER_NAME: ${{(on.email.outputs.from.value.name)}}
          SENDER_ADDRESS: ${{(on.email.outputs.from.value.address)}}
        run: |
          echo  $SUBJECT
          echo $DUE
          echo $CONTENT
          echo $SENDER_NAME
          echo $SENDER_ADDRESS
