on:
  email:
    imap:
      host: outlook.office365.com
      user: ${{secrets.EMAIL_USER}}
      password: ${{secrets.EMAIL_PASSWORD}}
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          pwd
          ls
      - name: Install Python
        run: |
          apt-get update
          apt-get install python3 -y
          apt-get install python3-pip -y
      - name: Install Packages
        run: |
          pip3 install todoist-python
          pip3 install markdownify
      - name: Update Todoist
        env:
          SUBJECT: ${{(on.email.outputs.subject)}}
          DUE: ${{(on.email.outputs.date)}}
          CONTENT: ${{(on.email.outputs.textAsHtml)}}
          SENDER: ${{(on.email.outputs.from.text)}}
          PROJECT: ${{secrets.PROJECT}}
          SECTION: ${{secrets.SECTION}}
        run: |
          pwd
          ls
          python3 ./dist/post_task.py
