on:
  email:
    imap:
      host: outlook.office365.com
      user: ${{secrets.EMAIL_USER}}
      password: ${{secrets.EMAIL_PASSWORD}}
jobs:
  print:
    name: ToTodoist
    runs-on: ubuntu-latest
    steps:
      - name: Update Subject
        env:
          AUTH: ${{secrets.AUTH}}
          SUBJECT: ${{(on.email.outputs.subject)}}
          DUE: ${{(on.email.outputs.date)}}
          PROJECT: ${{secrets.PROJECT}}
          SECTION: ${{secrets.SECTION}}
        run: |
          curl "https://api.todoist.com/rest/v1/tasks" \
          -X POST \
          --data "{\"content\": \"$SUBJECT\", \"project_id\": $PROJECT, \"section_id\": $SECTION, \"due_string\": \"$DUE\"}" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $AUTH" > task.json
      - name: Get task id
        id: taskid
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "task.json"
          prop_path: "id"
      - name: Update Comment
        env:
          AUTH: ${{secrets.AUTH}}
          CONTENT: ${{(on.email.outputs.text)}}
          SENDER: ${{(on.email.outputs.from.text)}}
        run: |
          curl "https://api.todoist.com/rest/v1/comments" \
          -X POST \
          --data "{\"task_id\":${{steps.taskid.outputs.prop}} ,\"content\":\"SENDER: $SENDER \n$CONTENT\"}" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $AUTH"
