on:
  email:
    imap:
      host: outlook.office365.com
      user: ${{secrets.EMAIL_USER}}
      password: ${{secrets.EMAIL_PASSWORD}}
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        run: |
          apt-get -y install python3.7
      - name: Install Packages
        run: |
          pip install todoist-python
          pip install markdownify
      - name: Update Todoist
        env:
          SUBJECT: ${{(on.email.outputs.subject)}}
          DUE: ${{(on.email.outputs.date)}}
          CONTENT: ${{(on.email.outputs.textAsHtml)}}
          SENDER: ${{(on.email.outputs.from.text)}}
          PROJECT: ${{secrets.PROJECT}}
          SECTION: ${{secrets.SECTION}}
        run: |
          python post_task.py
