on:
  email:
    imap:
      host: outlook.office365.com
      user: ${{secrets.EMAIL_USER}}
      password: ${{secrets.EMAIL_PASSWORD}}
jobs:
  print:
    name: ToTodoist
    runs-on: ubuntu-latest
    steps:
      - name: Update Subject
        env:
          AUTH: ${{secrets.AUTH}}
          SUBJECT: ${{(on.email.outputs.subject)}}
          DUE: ${{(on.email.outputs.date)}}
          PROJECT: ${{secrets.PROJECT}}
          SECTION: ${{secrets.SECTION}}
        run: |
          curl "https://api.todoist.com/rest/v1/tasks" \
          -X POST \
          --data "{\"content\": \"$SUBJECT\", \"project_id\": $PROJECT, \"section_id\": $SECTION, \"due_string\": \"$DUE\"}" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer $AUTH" > task.json
      - name: Get task id
        id: taskid
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "task.json"
          prop_path: "id"
      - name: Save HTML
        env:
          CONTENT: ${{(on.email.outputs.textAsHtml)}}
        run: |
          echo $CONTENT > content.html
      - name: Convert HTML to Markdown
        uses: docker://pandoc/core:2.9
        with:
          # args: "--from html --to markdown_strict -o content_md.txt content_html.txt"
          args: >-
            content.html
            --output=content.md
      - name: Update Comment
        env:
          AUTH: ${{secrets.AUTH}}
          SENDER: ${{(on.email.outputs.from.text)}}
          TASKID: ${{(steps.taskid.outputs.prop)}}
        run: |
          echo_command() { printf '%s\n' "${*}"; "${@}"; }
          cat content.md
          echo_command curl "https://api.todoist.com/rest/v1/comments" -X POST --data-binary @content.md  -H "Content-Type: application/json" -H "Authorization: Bearer $AUTH" -H "content-type: text/csv"
