on:
  email:
    imap:
      host: outlook.office365.com
      user: ${{secrets.EMAIL_USER}}
      password: ${{secrets.EMAIL_PASSWORD}}
jobs:
  print:
    name: ToTodoist
    runs-on: ubuntu-latest
    steps:
      - name: Update Todoist
        # uses: actionsflow/axios@v1
        env:
          AUTH: ${{secrets.AUTH}}
          SUBJECT: ${{(on.email.outputs.subject)}}
          DUE: ${{(on.email.outputs.date)}}
          CONTENT: ${{(on.email.outputs.textAsHtml)}}
          SENDER: ${{(on.email.outputs.from.text)}}
          PROJECT: ${{secrets.PROJECT}}
          SECTION: ${{secrets.SECTION}}
        # with:
        #   url: https://api.todoist.com/rest/v1/tasks
        #   method: "POST"
        #   headers: '{ "Authorization": "Bearer <<<${{env.AUTH}}>>>" }'
        #   data: '{"content": <<<${{env.SUBJECT}}>>>, "project_id": <<<${{env.PROJECT}}>>>, "section_id": <<<${{env.SECTION}}>>>, "due": {"string": <<<${{env.DUE}}>>>}}'
        run: |
          curl "https://api.todoist.com/rest/v1/tasks" \
          -X POST \
          --data "{\"content\": \"$SUBJECT\", \"project_id\": $PROJECT, \"section_id\": $SECTION, \"due_string\": \"$DUE\"}" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer e701c6367e592f6c90ad7c404ca0d1238b4b3571"
