on:
  email:
    imap:
      host: outlook.office365.com
      user: ${{secrets.EMAIL_USER}}
      password: ${{secrets.EMAIL_PASSWORD}}
jobs:
  print:
    name: ToTodoist
    runs-on: self-hosted
    steps:
      - name: Run python script
        env:
          AUTH: ${{secrets.AUTH}}
          PROJECT: ${{secrets.PROJECT}}
          SECTION: ${{secrets.SECTION}}
          SUBJECT: ${{(on.email.outputs.subject)}}
          DUE: ${{(on.email.outputs.date)}}
          SENDER: ${{(on.email.outputs.from.text)}}
          CONTENT: ${{(on.email.outputs.text)}}
        run: |
          python post_task.py
